### ISSUE TITLE
Doesn't allow current puppet-lint version

### ISSUE THREAD

**Issue by genebean** [deanwilson/puppet-lint-absolute_template_path-check#110]
IT seems this requires puppet-lint < 3.0 while other gems I use such as `voxpupuli-puppet-lint-plugins` require puppet-lint ~> 3.1. Can this get updated to allow for the current version?

**Comment by deanwilson** [comment]
Thank you for reporting this. I've published a fixed version on [RubyGems](https://rubygems.org/gems/puppet-lint-absolute_template_path) but as it's removing a supported version of a few things (including ruby itself) I've bumped its major version.
