### ISSUE TITLE
Wrong links on Rubygems

### ISSUE THREAD

**Issue by mtancoigne** [deanwilson/puppet-lint-absolute_template_path-check#84]
Hi!

On the [Rubygem page](https://rubygems.org/gems/puppet-lint-absolute_template_path), the link to _Homepage_ points to the old repository (`absolute_template_path` instead of `absolute_template_path-check`). 

Is it possible to update it ?

**Comment by deanwilson** [comment]
This has now been fixed on [RubyGems](https://rubygems.org/gems/puppet-lint-absolute_template_path). Apologies for the huge delay.
